apiVersion: apps/v1
kind: Deployment
metadata:
  name: temprerature-prediction
  labels:
    app: temprerature_prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temprerature_prediction
  template:
    metadata:
      labels:
        app: temprerature_prediction
    spec:
      containers:
      - name: temprerature-prediction
        image: 606010182123.dkr.ecr.us-east-1.amazonaws.com/temprerature_prediction:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
        - name: DAGSHUB_TOCKEN 
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: DAGSHUB_TOCKEN
        - name: DAGSHUB_REPO_OWNER
          value: "wadoodabdulwadood122010"
        - name: DAGSHUB_REPO_NAME
          value: "Temperature-prediction-Mlops-project"
        

---
apiVersion: v1
kind: Service
metadata:
  name: temprerature-prediction-services 
spec:
  type: LoadBalancer
  selector:
    app: temprerature_prediction 
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000