apiVersion: apps/v1
kind: Deployment
metadata:
  name: temprerature-prediction
  labels:
    app: my_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: temprerature-prediction
        image: 606010182123.dkr.ecr.us-east-1.amazonaws.com/my_app:V3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: DAGSHUB_TOCKEN 
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: DAGSHUB_TOCKEN
        - name: DAGSHUB_REPO_OWNER
          value: "wadoodabdulwadood122010"
        - name: DAGSHUB_REPO_NAME
          value: "Temperature-prediction-Mlops-project"
        

---
apiVersion: v1
kind: Service
metadata:
  name: temprerature-prediction-services 
spec:
  type: LoadBalancer
  selector:
    app: my_app 
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000